name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Verify repository structure
        run: ls -la

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ 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 }}
          publish_dir: hrms-sys/public
          publish_branch: gh-pages
          allow_empty_commit: false
          keep_files: false
          force_orphan: false
          enable_jekyll: false
          disable_nojekyll: false
          exclude_assets: .github

      - name: Post telemetry data on failure
        if: failure()
        run: |
          gh api -X POST "repos/ezra-6987/hrms/pages/telemetry" \
            -F github_run_id="${{9430366857}}" \
            -F conclusion="failure"
        env:
          GITHUB_TOKEN: ${{ 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 }}
