name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./hrms-sys/views
          destination: https://ezra-6987.github.io/hrms/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hrms-artifact
          path: ./hrms-sys

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: hrms-artifact
          path: ./hrms-sys
          run-id: 9430366857
          merge-multiple: false
          repository: ezra-6987/hrms
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cleanup: false  # Keep generated files from the build
          target_branch: gh-pages  # Specify the branch for GitHub Pages
          publish_dir: https://ezra-6987.github.io/hrms/
