name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./hrms-sys/views
          destination: ./hrms-sys/_site

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hrms-artifact
          path: ./hrms-sys/_site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: hrms-artifact
          path: ./hrms-sys/_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          timeout: 600000
          error_count: 10
          reporting_interval: 5000
          artifact_name: hrms-artifact
          preview: false
