name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./hrms-sys/views
          destination: https://ezra-6987.github.io/hrms/
      - name: Check Content Size
        run: |
          content_size=$(du -sh ./hrms-sys | cut -f1)
          echo "Content size: $content_size"
          if [[ $content_size > 10G ]]; then
            echo "Error: Content size exceeds 10GB limit."
            exit 1
          else
            echo "Content size within limit."
          fi
      - name: Clean up artifacts
        run: |
          # Remove hard links
          find ./hrms-sys -type f -links +1 -exec rm {} +
          # Remove symlinks
          find ./hrms-sys -type l -exec rm {} +
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hrms-artifact
          path: ./hrms-sys

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build.outputs.artifacts_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: hrms-artifact
          path: ./hrms-sys
      - name: Check Content Size
        run: |
          content_size=$(du -sh ./hrms-sys | cut -f1)
          echo "Content size: $content_size"
          if [[ $content_size > 10G ]]; then
            echo "Error: Content size exceeds 10GB limit."
            exit 1
          else
            echo "Content size within limit."
          fi
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GH_TOKEN}}
          timeout: 600000
          error_count: 10
          reporting_interval: 5000
          artifact_name: hrms-artifact
          preview: false
